<h1> Introduction to Pytorch </h1>

This is just an attempt to learn pytorch and switch to pytorch framework from scratch and most of the references I have collected for this comes from: https://www.learnpytorch.io . Please Refer to the site for more accurate informations as mine might have alot of flaws. 

In [1]:
import torch
import numpy as np 

<h5> Pytroch Version </h5>

We can check the version of the pytorch using the command as '''torch. _ _ version _ _'''


In [2]:
torch.__version__

'2.0.1+cu118'

<h5><u> Tensor </u> </h5>
<ul>
    <li> Tensors are fundamental building blocks of Machine Learning </li>
    <li> It Represents data in Numerical way </li>
    <li> To Create tensor in pytorch we have code as: <br> torch.tensor([1,2]) </li>
    <li> Tensor can be created from python list, numpy array and many more </li>
    <li> Each tensor has its own dimension (How many dimensions does each tensor has can be computed by how many consecutive big brackets are there on the left most side )</li>
    <li> Each tensor has its own shape (total number of elements, rowwise, column wise and product of all gives all elements)</li>
    <li> Can Check the dimension and shape of tensor with these code 'tensor_variable.ndim','tensor_variable.shape'</li>
</ul>


In [3]:
one_dim_tensor=torch.tensor([1,2])
print(one_dim_tensor)
print(type(one_dim_tensor))
print(one_dim_tensor.ndim)
print(one_dim_tensor.shape)
print('\n'+'--'*40)

three_dim_tensor=torch.tensor(np.array([[[1,2,3],
                                        [4,5,6],
                                        [7,8,9]]]))
print(three_dim_tensor)
print(three_dim_tensor.ndim)
print(three_dim_tensor.shape)
print('\n'+'--'*40)

#This following one represents 3x3 representation that is the order in which most images exist
three_dim_tensor_3=torch.tensor(np.array([[[1,2,3],
                                        [4,5,6],
                                        [7,8,9]],
                                        [[10,11,12],
                                        [13,14,15],
                                        [16,17,18]],
                                        [[19,20,21],
                                        [22,23,24],
                                        [25,26,27]]]))
print(three_dim_tensor_3)
print(three_dim_tensor_3.ndim)
print(three_dim_tensor_3.shape)
print('\n'+'--'*40)

tensor([1, 2])
<class 'torch.Tensor'>
1
torch.Size([2])

--------------------------------------------------------------------------------
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32)
3
torch.Size([1, 3, 3])

--------------------------------------------------------------------------------
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]], dtype=torch.int32)
3
torch.Size([3, 3, 3])

--------------------------------------------------------------------------------



<h5><u> Scalar</u></h5>
<ul>
    <li> Scalar is a single number in tensor-terms it's a zero dimension tensor </li>
    <li> scalar example can be seen as scalar =torch.tensor(7) (Note: No big brackets so its zero dimensions, Else number of big brackets on left most side number of dimensons) </li>
    <li> Can Verify if scalar or not by checking its dimension as scalar.ndim (From above example) </li>
</ul>

In [4]:
scalar_val=torch.tensor(7)
print(scalar_val)
print(f'Dimenson of the Scalar value: {scalar_val.ndim}')

tensor(7)
Dimenson of the Scalar value: 0


<h3><u> Vector </u></h3>
<ul>
    <li>Vector are single dimension tensor but can contain many numbers </li>
    <li>So We can use vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house. </li>
    <li>In Simplest term we can understand it as 1 dimensional array/list which can be used to represents many real world values in numerical way </li> 


In [5]:
room_details=torch.tensor([3,2])
display(room_details)
display(room_details.ndim)
display(room_details.shape)

tensor([3, 2])

1

torch.Size([2])

<h5><u> Matrix </u></h5>
<ul>
    <li> Matrix is a 2 dimensional array </li>
</ul>

In [6]:
matrix=torch.tensor([[1,2],
                     [3,4]])

display(matrix)
display(matrix.ndim)
display(matrix.shape)

tensor([[1, 2],
        [3, 4]])

2

torch.Size([2, 2])

<h5> Summary </h5>
To Sum it up in a single table we have: 
<table>
  <tr>
    <th>Name</th>
    <th>What is it?</th>
    <th>Number of dimensions</th>
    <th>Lower or upper (usually/example)</th>
  </tr>
  <tr>
    <td>scalar</td>
    <td>a single number</td>
    <td>0</td>
    <td>Lower (a)</td>
  </tr>
  <tr>
    <td>vector</td>
    <td>a number with direction (e.g. wind speed with direction) but can also have many other numbers</td>
    <td>1</td>
    <td>Lower (y)</td>
  </tr>
  <tr>
    <td>matrix</td>
    <td>a 2-dimensional array of numbers</td>
    <td>2</td>
    <td>Upper (Q)</td>
  </tr>
  <tr>
    <td>tensor</td>
    <td>an n-dimensional array of numbers</td>
    <td>can be any number</td>
    <td>Upper (X)</td>
  </tr>
</table>	
<br>

To Sum it up in single Image we have: 
<br>
<img width=800 height=400 src='https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png'>

<h5> Initliazation of Tensors </h5>

<h5> Random tensors </h5>
    &nbsp;&nbsp;&nbsp;Initially all weights are random and they are adjusted overtime so its a must to be able to create a random tensor for that very purpose. 'torch.rand()' is used to create random tensor with size parameter present in it.
    

In [7]:
initial_weights=torch.rand(size=(3,3))
print(initial_weights)
print('\n'+'--'*25)
initial_image=torch.rand(size=(224,224,3)) #224 rows 224 columns and having 3 channels 
print((initial_image.shape,initial_image.ndim))

tensor([[0.4944, 0.0365, 0.2384],
        [0.7129, 0.8937, 0.9390],
        [0.8411, 0.8100, 0.9232]])

--------------------------------------------------
(torch.Size([224, 224, 3]), 3)


<h5> Zero and Ones Tenssors </h5>
&nbsp;&nbsp;&nbsp; Sometimes the tensors should be initilaized at 0 we can do that as 'torch.zeros()' putting size as parameter. Similarly we can have a tensor with only 1s present on it like 'torch.ones()' with size as parameter

In [8]:
zero_tensor=torch.zeros(size=(3,3,3))
print(zero_tensor)
print('\n'+'--'*25)

ones_tensor=torch.ones(size=(3,3,3))
print(ones_tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

--------------------------------------------------
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


<h5> Tensor within Range </h5>

In [9]:
tensor_from_1_to_10=torch.arange(1,11)
tensor_from_1_to_10

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h5> Operations in Tensor </h5>
<p> We can carry out various operations in the tensors with few lines of code.</p>

In [10]:

print(f'Addition: {tensor_from_1_to_10+10}\n')
print(f'Addition using torch add : {torch.add(tensor_from_1_to_10,10)}\n')
print(f'Multiplication: {tensor_from_1_to_10*10}\n')
print(f'Multiplication using torch multiply: {torch.multiply(tensor_from_1_to_10,10)}\n')
print(f'Division by 10: {tensor_from_1_to_10/10}\n')
print(f'Division by 10 using torch divide: {torch.divide(tensor_from_1_to_10,10)}\n')

Addition: tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Addition using torch add : tensor([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Multiplication: tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Multiplication using torch multiply: tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Division by 10: tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

Division by 10 using torch divide: tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

