<h3> Tensor Data types </h3>

Tensors are pretty confusing to deal with at first because there are many different types of tensor datatypes in pytorch <br>
Some are specific to CPU other are better for GPU <br>

Tensors also have bits as torch.float32 torch.float16 torch.float8 and so on.<br>
In simplest understanding term we can understand that higher bit or precision value means more detail can be obtained and carried over <br>
but are comparatively slower then lower precision value <br>

Some major issues we come across while handling tensors are: 
<ol>
    <li> datatype issue where the 2 tensors won't have same datatype format (float32 and float16) </li>
    <li> device issue where the tensor is deisgned to work on CPU and other is designated to work for GPU </li>
</ol>

Below we can observe different tensor types with precision values.


In [5]:
import torch
import numpy as np 

float_32_tensor=torch.tensor([0.3245671892,0.55341245,0.11234153],dtype=torch.float32,device=None,requires_grad=False)
print(float_32_tensor,float_32_tensor.dtype,float_32_tensor.device)

float_16_tensor=torch.tensor([0.3245671892,0.55341245,0.11234153],dtype=torch.float16,device=None,requires_grad=False)
print(float_16_tensor,float_16_tensor.dtype,float_16_tensor.device)

tensor([0.3246, 0.5534, 0.1123]) torch.float32 cpu
tensor([0.3245, 0.5532, 0.1124], dtype=torch.float16) torch.float16 cpu


<h3> Matrix Multiplication </h3>

We can easily say that matrix multiplication is the backbone of neural network architechture, <br>
Since we have multiple  neurons with their own weights and biases resulting in structures having alot of outputs with many more operations which be optimized by using matrix multiplication<br>
<br>
PyTorch implements matrix multiplication functionality in the torch.matmul() or torch.mm() method.

<h4> Rule for Matrix Multiplication: </h4>
<img width=800 height=500 src='https://i.ytimg.com/vi/M5TsRZt3mis/maxresdefault.jpg'>

In [6]:
Matrix_A=torch.tensor(np.asarray([[2,1],
                                [1,2]]),dtype=torch.float32)

Matrix_B=torch.tensor(np.asarray([[3,1,5],
                                  [2,2,3]]),dtype=torch.float32)

print(f'Matirx A: \n {Matrix_A} \n Dimension of Matrix A: \n {Matrix_A.shape}')
print('\n\n')
print(f'Matirx B: \n {Matrix_B} \n Dimension of Matrix B: \n {Matrix_B.shape}')
print('\n\n')

Output_Matrix=torch.matmul(Matrix_A,Matrix_B)
print(f'Output Matrix: \n {Output_Matrix}\n Dimension of Output Matrix: \n {Output_Matrix.shape}')


Matirx A: 
 tensor([[2., 1.],
        [1., 2.]]) 
 Dimension of Matrix A: 
 torch.Size([2, 2])



Matirx B: 
 tensor([[3., 1., 5.],
        [2., 2., 3.]]) 
 Dimension of Matrix B: 
 torch.Size([2, 3])



Output Matrix: 
 tensor([[ 8.,  4., 13.],
        [ 7.,  5., 11.]])
 Dimension of Output Matrix: 
 torch.Size([2, 3])


<h3> Transpose of Matrix </h3>

<p>Transpose of a matrix is one of the most commonly used methods in matrix transformation. For a given matrix, the transpose of a matrix is obtained by interchanging rows into columns or columns to rows. <br> It can be done for purpose of preparing matrix for matrix multiplication, finding out inverse of a matrix and many more. </p>

<img  align='left' height=300 width=800 src='https://cdn1.byjus.com/wp-content/uploads/2021/09/Important-Questions-for-Class-10-Maths-Chapter-8-Introduction-to-Trigonometry-1.png'>

<p>
    &nbsp;&nbsp;Matrix Tranpose can be done on pytorch with<br>
    <ol>
        <li> 1.  ''' torch.tranpose(input,dim0,dim1) ''' : where input is desired tensor to tranpose and dim0 and dim1 are the dimension to be swapped.</li><br>
        <li> 2.  ''' tensor.T ''' : where tensor is the desired tensor to tranpose.</li>
    <ol>
</p>
<br><br><br><br><br><br>
<h4 align='left'> Example</h4>
 Assuming we have a matrix A as shown in the figure above: <br>
 A=[[1,2,3],<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    [4,5,6]]
<br><br>
B=[[7,8], <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   [9,10]]

As it stands right now A has dimensions as: 2x3 and B has dimensions as: 2x2 
right now the 2 cannot be multiplied. Solve it: 
 

In [3]:
A=torch.tensor(np.asarray([[1,2,3],
                           [4,5,6]]),dtype=torch.float32,device=None, requires_grad=False)

print(f'Matrix A:\n {A} \n\nDimensions: {A.shape} ')

#Getting Transpose to change dimensions from 2,3 to 3,2 which makes it possible to have matrix multplication with B having 2x2 resulting in output of 3,2 dimension
A=A.T

print('-'*50)
print(f'Matrix A Transposed:\n {A} \n\nDimensions: {A.shape}')
print('-'*50)

B=torch.tensor(np.asarray([[7,8],
                            [9,10]]),dtype=torch.float32,device=None,requires_grad=False)

output=torch.matmul(A,B)

print(f'Matrix Multiplication Output:\n {output} \n\n Dimension of Output: {output.shape}')

Matrix A:
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

Dimensions: torch.Size([2, 3]) 
--------------------------------------------------
Matrix A Transposed:
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]]) 

Dimensions: torch.Size([3, 2])
--------------------------------------------------
Matrix Multiplication Output:
 tensor([[43., 48.],
        [59., 66.],
        [75., 84.]]) 

 Dimension of Output: torch.Size([3, 2])


<h3> Converting Numpy array to Tensor and viceversa </h3>
We can convert numpy arrays to tensors and also viceversa with syntax as: 
<ul>
    <li> ''' torch.from_numpy(numpy_arr) ''' : Converts numpy array to tensors </li>
    <li> ''' tensor_to_convert.numpy() ''' : The output of this gives numpy array from tensor </li>
</ul>

In [21]:
tensor_one=torch.ones(10)
numpy_one_arr=tensor_one.numpy()

print(f'Tensor Found: {tensor_one}\n')
print(f'Numpy Conerted: {numpy_one_arr}')

numpy_two_arr=np.arange(1,10)
print(f'Numpy Two: {numpy_two_arr}')
print(f'Tensor Converted: {torch.from_numpy(numpy_two_arr).type(torch.float32)}')


Tensor Found: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Numpy Conerted: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Numpy Two: [1 2 3 4 5 6 7 8 9]
Tensor Converted: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


<h3> Coding questions for Tensors and basics pytorch </h3>

Till here most of the basics of pytorch and tensors have been covered now we have few coding questions that can flesh out our learning of pytorch in general.

<ol>
    <li>Given two tensors 'a' and 'b', write a code snippet to perform element-wise addition of the two tensors and store the result in a new tensor c. Print the resulting tensor 'c'. 
        <ul>
            <li> Same length Tensors </li>
            <li> Different Length Tensors </li>
        </ul>
    </li>
</ol>

In [67]:
import random
import time
#For Same length: 
a=torch.ones(5).type(torch.int16)
b=torch.arange(0,5).type(torch.int16)
c=a+b 
print(f'output same length tensors : {c.tolist()}')

output same length tensors : [1, 2, 3, 4, 5]


In [97]:

#For different length: 
t_s=time.time()

a=torch.tensor([random.randrange(0,10) for i in range(0,random.randrange(5,25))])
b=torch.tensor([random.randrange(0,10) for i in range(0,random.randrange(1,10))])

print(f'Tensor A: {a}')
print(f'Tensor B: {b}')

a=a.tolist()
b=b.tolist()


range_val=max([len(a),len(b)])
c=[]
for i in range(range_val):
    try:
        c.append(a[i]+b[i])
    except:
        try:
            c.append(a[i])
        except:
            c.append(b[i])

print(f'Torch C: {torch.from_numpy(np.array(c))}')
t_e=time.time()
print(f'Execution Time: {(t_e-t_s)*1000} ms')

Tensor A: tensor([3, 1, 9, 2, 9, 7, 6, 0])
Tensor B: tensor([8, 3, 9, 1, 2, 0, 9, 8])
Torch C: tensor([11,  4, 18,  3, 11,  7, 15,  8], dtype=torch.int32)
Execution Time: 2.0189285278320312 ms
