<h3> Tensor Data types </h3>

Tensors are pretty confusing to deal with at first because there are many different types of tensor datatypes in pytorch <br>
Some are specific to CPU other are better for GPU <br>

Tensors also have bits as torch.float32 torch.float16 torch.float8 and so on.<br>
In simplest understanding term we can understand that higher bit or precision value means more detail can be obtained and carried over <br>
but are comparatively slower then lower precision value <br>

Some major issues we come across while handling tensors are: 
<ol>
    <li> datatype issue where the 2 tensors won't have same datatype format (float32 and float16) </li>
    <li> device issue where the tensor is deisgned to work on CPU and other is designated to work for GPU </li>
</ol>

Below we can observe different tensor types with precision values.


In [1]:
import torch
import numpy as np 

float_32_tensor=torch.tensor([0.3245671892,0.55341245,0.11234153],dtype=torch.float32,device=None,requires_grad=False)
print(float_32_tensor,float_32_tensor.dtype,float_32_tensor.device)

float_16_tensor=torch.tensor([0.3245671892,0.55341245,0.11234153],dtype=torch.float16,device=None,requires_grad=False)
print(float_16_tensor,float_16_tensor.dtype,float_16_tensor.device)

tensor([0.3246, 0.5534, 0.1123]) torch.float32 cpu
tensor([0.3245, 0.5532, 0.1124], dtype=torch.float16) torch.float16 cpu


<h3> Matrix Multiplication </h3>

We can easily say that matrix multiplication is the backbone of neural network architechture, <br>
Since we have multiple  neurons with their own weights and biases resulting in structures having alot of outputs with many more operations which be optimized by using matrix multiplication<br>
<br>
PyTorch implements matrix multiplication functionality in the torch.matmul() method.

<h4> Rule for Matrix Multiplication: </h4>
<img width=800 height=500 src='https://i.ytimg.com/vi/M5TsRZt3mis/maxresdefault.jpg'>

In [16]:
Matrix_A=torch.tensor(np.asarray([[2,1],
                                [1,2]]),dtype=torch.float32)

Matrix_B=torch.tensor(np.asarray([[3,1,5],
                                  [2,2,3]]),dtype=torch.float32)

print(f'Matirx A: \n {Matrix_A} \n Dimension of Matrix A: \n {Matrix_A.shape}')
print('\n\n')
print(f'Matirx B: \n {Matrix_B} \n Dimension of Matrix B: \n {Matrix_B.shape}')
print('\n\n')

Output_Matrix=torch.matmul(Matrix_A,Matrix_B)
print(f'Output Matrix: \n {Output_Matrix}\n Dimension of Output Matrix: \n {Output_Matrix.shape}')


Matirx A: 
 tensor([[2., 1.],
        [1., 2.]]) 
 Dimension of Matrix A: 
 torch.Size([2, 2])



Matirx B: 
 tensor([[3., 1., 5.],
        [2., 2., 3.]]) 
 Dimension of Matrix B: 
 torch.Size([2, 3])



Output Matrix: 
 tensor([[ 8.,  4., 13.],
        [ 7.,  5., 11.]])
 Dimension of Output Matrix: 
 torch.Size([2, 3])
