In [7]:
import torch
import numpy as np 

<h5> Pytroch Version </h5>

We can check the version of the pytorch using the command as '''torch. _ _ version _ _'''


In [2]:
torch.__version__

'2.0.1+cu118'

<h5><u> Tensor </u> </h5>
<ul>
    <li> Tensors are fundamental building blocks of Machine Learning </li>
    <li> It Represents data in Numerical way </li>
    <li> To Create tensor in pytorch we have code as: <br> torch.tensor([1,2]) </li>
    <li> Tensor can be created from python list, numpy array and many more </li>
    <li> Each tensor has its own dimension (How many dimensions does each tensor has can be computed by how many consecutive big brackets are there on the left most side )</li>
    <li> Can Check the dimension and shape of tensor with these code 'tensor_variable.ndim','tensor_variable.shape'</li>
</ul>


In [25]:
one_dim_tensor=torch.tensor([1,2])
print(one_dim_tensor)
print(type(one_dim_tensor))
print(one_dim_tensor.ndim)
print(one_dim_tensor.shape)
print('\n'+'--'*40)

three_dim_tensor=torch.tensor(np.array([[[1,2,3],
                                        [4,5,6],
                                        [7,8,9]]]))
print(three_dim_tensor)
print(three_dim_tensor.ndim)
print(three_dim_tensor.shape)
print('\n'+'--'*40)

#This following one represents 3x3 representation that is the order in which most images exist
three_dim_tensor_3=torch.tensor(np.array([[[1,2,3],
                                        [4,5,6],
                                        [7,8,9]],
                                        [[10,11,12],
                                        [13,14,15],
                                        [16,17,18]],
                                        [[19,20,21],
                                        [22,23,24],
                                        [25,26,27]]]))
print(three_dim_tensor_3)
print(three_dim_tensor_3.ndim)
print(three_dim_tensor_3.shape)
print('\n'+'--'*40)

tensor([1, 2])
<class 'torch.Tensor'>
1
torch.Size([2])

--------------------------------------------------------------------------------
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32)
3
torch.Size([1, 3, 3])

--------------------------------------------------------------------------------
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]], dtype=torch.int32)
3
torch.Size([3, 3, 3])

--------------------------------------------------------------------------------



<h5><u> Scalar</u></h5>
<ul>
    <li> Scalar is a single number in tensor-terms it's a zero dimension tensor </li>
    <li> scalar example can be seen as scalar =torch.tensor(7) (Note: No big brackets so its zero dimensions, Else number of big brackets on left most side number of dimensons) </li>
    <li> Can Verify if scalar or not by checking its dimension as scalar.ndim (From above example) </li>
</ul>

In [34]:
scalar_val=torch.tensor(7)
print(scalar_val)
print(f'Dimenson of the Scalar value: {scalar_val.ndim}')

tensor(7)
Dimenson of the Scalar value: 0


<h3><u> Vector </u></h3>
<ul>
    <li>Vector are single dimension tensor but can contain many numbers </li>
    <li> So We can use vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house. </li>


In [40]:
room_details=torch.tensor([3,2])
display(room_details)
display(room_details.ndim)

tensor([3, 2])

1